name: Windows Pipeline

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Install linked-deps
        working-directory: playwright-project
        run: npm i

      - name: Saucectl RUN Docker and Cloud
        uses: saucelabs/saucectl-run-action@v1
        with:
          concurrency: 2
