name: Windows Pipeline

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Install linked-deps
        working-directory: playwright-project
        run: npm i

      - name: Show linked-deps
        working-directory: playwright-project
        run: ls -la ./node_modules/

      - uses: saucelabs/saucectl-run-action@6a3e74d65212bce42174ba47de9fbf168f5d1f2a
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          working-directory: ./playwright-project/
          concurrency: 2

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Install linked-deps
        working-directory: playwright-project
        run: npm i

      - name: Show linked-deps
        working-directory: playwright-project
        run: Get-ChildItem -Recurse -Path ./node_modules/

      - uses: saucelabs/saucectl-run-action@6a3e74d65212bce42174ba47de9fbf168f5d1f2a
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          working-directory: ./playwright-project/
          concurrency: 2


  macosin-depth:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Install linked-deps
        working-directory: playwright-project
        run: npm i

      - name: Show linked-deps
        working-directory: playwright-project
        run: ls -la ./node_modules/

      - uses: saucelabs/saucectl-run-action@6a3e74d65212bce42174ba47de9fbf168f5d1f2a
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          working-directory: ./playwright-project/subproject/
          concurrency: 2

  windows-in-depth:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Install linked-deps
        working-directory: playwright-project
        run: npm i

      - name: Show linked-deps
        working-directory: playwright-project
        run: Get-ChildItem -Recurse -Path ./node_modules/

      - uses: saucelabs/saucectl-run-action@6a3e74d65212bce42174ba47de9fbf168f5d1f2a
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          working-directory: ./playwright-project/subproject/
          concurrency: 2
